import { CommonModule } from '@angular/common';
import { DestroyRef, ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { environment } from '../../../../environments/environment';
import { Instrument, InstrumentIssue, InstrumentIssueRequest, PagedResponse } from '../../../core/models/access-control.model';
import { AccessControlService } from '../../../core/services/access-control.service';
import { BreadcrumbComponent } from '../../../shared/breadcrumb/breadcrumb.component';
import { ConfirmationDialogService } from '../../../shared/components/confirmation-dialog';
import { ToastService } from '../../../shared/components/toast';

@Component({ selector: 'app-instrument-issue-form', standalone: true, imports: [CommonModule, ReactiveFormsModule, BreadcrumbComponent], templateUrl: './instrument-issue-form.component.html', styleUrl: './instrument-issue-form.component.scss', changeDetection: ChangeDetectionStrategy.OnPush })
export class InstrumentIssueFormComponent {
  private readonly destroyRef = inject(DestroyRef); private readonly fb = inject(FormBuilder); private readonly service = inject(AccessControlService); private readonly router = inject(Router); private readonly route = inject(ActivatedRoute); private readonly dialogService = inject(ConfirmationDialogService); private readonly toastService = inject(ToastService);
  readonly instruments = signal<Instrument[]>([]); readonly isLoading = signal(false); readonly isSubmitting = signal(false); readonly correlationId = signal<string | null>(null); readonly pageTitle = signal('Issue Instrument'); readonly selectedPhoto = signal<File | null>(null); readonly selectedPhotoPreviewUrl = signal<string | null>(null); readonly currentPhotoUrl = signal<string | null>(null); readonly statuses = ['Issued', 'Returned'];
  form = this.fb.group({ instrumentCorrelationId: ['', Validators.required], status: ['Issued', Validators.required], issuedTo: ['', [Validators.required, Validators.maxLength(200)]], department: ['', Validators.maxLength(150)], issueDate: [new Date().toISOString().slice(0, 10), Validators.required], returnDate: [''], remarks: ['', Validators.maxLength(1000)] });
  constructor() { const id = this.route.snapshot.paramMap.get('id'); if (id) { this.correlationId.set(id); this.pageTitle.set('Edit Instrument Issue'); } this.loadPage(id); }
  onPhotoSelected(event: Event): void { const file = (event.target as HTMLInputElement).files?.[0] ?? null; this.selectedPhoto.set(file); this.selectedPhotoPreviewUrl.set(file ? URL.createObjectURL(file) : null); if (file) this.form.markAsDirty(); }
  removePhoto(input: HTMLInputElement): void { input.value = ''; this.selectedPhoto.set(null); this.selectedPhotoPreviewUrl.set(null); this.currentPhotoUrl.set(null); this.form.markAsDirty(); }
  onSubmit(): void { if (this.form.invalid) { Object.values(this.form.controls).forEach(c => c.markAsTouched()); this.toastService.warning('Please complete required fields.', 'Issue needs attention'); return; } if (!this.hasPhoto()) { this.toastService.warning('Please upload an issue photo before saving.', 'Photo required'); return; } const id = this.correlationId(); const value = this.form.getRawValue(); const request: InstrumentIssueRequest = { instrumentCorrelationId: value.instrumentCorrelationId ?? '', status: value.status ?? 'Issued', issuedTo: value.issuedTo ?? '', department: value.department ?? undefined, issueDate: value.issueDate ?? new Date().toISOString().slice(0, 10), returnDate: value.returnDate ?? undefined, remarks: value.remarks ?? undefined, photoUrl: this.currentPhotoUrl() ?? undefined }; this.isSubmitting.set(true); const op = id ? this.service.updateInstrumentIssue(id, request, this.selectedPhoto()) : this.service.createInstrumentIssue(request, this.selectedPhoto()); op.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.isSubmitting.set(false); this.toastService.success('Instrument issue saved successfully.', 'Issue saved'); this.router.navigate(['/instrument-issues']); }, error: e => { this.isSubmitting.set(false); this.toastService.error(e?.error?.message || 'We could not save this issue.', 'Save failed'); } }); }
  onCancel(): void { if (!this.form.dirty) { this.router.navigate(['/instrument-issues']); return; } this.dialogService.showWarning('Unsaved Changes', 'You have unsaved changes.', 'Discard these changes and leave?').then(c => { if (c) this.router.navigate(['/instrument-issues']); }); }
  getPhotoUrl(url: string | null): string { if (!url) return ''; if (/^https?:\/\//i.test(url)) return url; return `${environment.apiBaseUrl.replace(/\/api\/?$/, '')}${url}`; }
  private loadPage(id: string | null): void { this.isLoading.set(true); this.service.getInstruments(1, 500).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: r => { this.instruments.set((r.data as PagedResponse<Instrument> | undefined)?.items ?? []); if (id) this.loadIssue(id); else this.isLoading.set(false); }, error: e => { this.isLoading.set(false); this.toastService.error(e?.error?.message || 'We could not load instruments.', 'Instruments not loaded'); } }); }
  private loadIssue(id: string): void { this.service.getInstrumentIssue(id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: r => { const issue = r.data as InstrumentIssue | undefined; if (issue) { this.form.patchValue({ ...issue, issueDate: issue.issueDate?.slice(0, 10), returnDate: issue.returnDate?.slice(0, 10) ?? '' }); this.currentPhotoUrl.set(issue.photoUrl ?? null); } this.isLoading.set(false); }, error: e => { this.isLoading.set(false); this.toastService.error(e?.error?.message || 'We could not load this issue.', 'Issue not loaded'); } }); }
  private hasPhoto(): boolean { return !!this.selectedPhoto() || !!this.currentPhotoUrl(); }
}
